---
title: "intro"
output: pdf_document
---

Across the developing and developed world, citizens rely on governments for routine access to basic services such as healthcare and education. Public service delivery systems, managed and executed daily bureaucrats and elected officials, serve millions of citizens each and every day. These systems are expected to lift social welfare: educate children, cure diseases, prevent crime. Where these services flourish, run by an efficient personnel and well-managed by politicians, societies thrive. When they fail, the cost is immense.

This dissertation began as an intellectual journey into understanding public services from an administrative perspective. From 2013 to 2015, I had the opportunity of interviewing municipal bureaucrats and politicians in small municipalities across the Peruvian Andes, learning from their hands on experience the challenge of public service delivery. In this journey I was fascinated by the herculean task of administering over precarious services such as healthcare and education. In particular, personnel management rose to the forefront of these local concerns. I quickly realized that analyzing how political decisions shaping bureaucratic personnel could have a profound impact on how public services were delivered.

It may be worthwhile reiterating this. Education and healthcare do not simply materialize when a politician decides to redistribute public (or private) goods, however defined, to citizens.^[@pepinsky_bureaucracy_2017.] These benefits materialize when investments occur in the personnel necessary to provide citizens with these public services. These investments in personnel, suffices to say, are often found wanting in the developing world. Institutional features such as staff turnover, morale, expertise are products of political decisions made political principals.^[@akhtari_bureaucratic_1997, @suleiman_dismantling_2013.] The question is what shapes these political administrative decisions. What are the electoral payoffs principals receive for improving public service delivery? How does personnel management affect the quality of services? And what are its implications for social welfare?

Public administration is inevitably political. My inquiry into the determinants of managerial decisions starts from an explicit theory of the strategic calculations of mayors, embedded in an electoral accountability framework.^[For seminal works on this tradition, see @ferejohn_incumbent_1983, @barro_control_1973.] In doing so, I anchor political administration as an electoral game, building on the seminal work of @geddes_politicians_1994.^[Here, and throughout the dissertation, I refer to the mayor with the female pronoun.] In Brazil, as in many countries across the world, executive leaders enjoys large discretion in whom to appoint into and dismiss from bureaucracies.^[In the United States, this practice is often referred to as the Plum Book. In Brazil, mayors can appoint and dismiss bureaucrats, with the notable exception of civil servants who comprise (a rapidly falling) majority of teachers.] Once in office, the mayor decides how to manage the bureaucratic apparatus she inherits from the previous administration. An eye towards reelection, and another to the political arena facing the mayor today, shapes this calculation.

This dissertation asks an overarching question, which I decompose into three interconnected inquiries. Under what conditions do local politicians reshape bureaucratic structures to improve the quality of the administrative staff responsible for public service delivery? To answer this, I proceed through backward induction, looking first at the electoral payoffs of improving public service delivery. Are mayors rewarded for improving public service delivery, when running up for reelection? Second, what consequences do practices associated with personnel management, such as bureaucratic turnover, have over public service delivery? Finally, how does the executive-legislative bargain affect personnel decisions? How does the need to negotiate with legislative actors, exchanging public sector jobs for budgetary support, shape bureaucratic turnover?

In seeking for evidence to answer this inquiry, I have collected and systematized an exhaustive dataset on all bureaucrats hired by municipal governments in Brazil from the transition to democracy (1988) to 2015. This dataset contains information about managers and street-level bureaucrats, providing us with a radiography of the administrative innards of Brazil's localized state.^[@fukuyama_what_2013.] I have structured an electoral dataset containing all politicians, mayors and city councillors, across all municipalities: this allows me to follow their political trajectories as they reshape bureaucracies through their managerial decisions. Finally, I provide measures (albeit imperfect) of the quality of public services: student test scores and infant mortality rates provide us with estimates of how well public services are operating at the local level.

For scholars analyzing states in the developing world, often performed in a historical institutional framework, data collection and systematic analysis demands a herculean effort. For contemporary analysis of state bureaucracies, the task is similarly daunting.^[@fukuyama_what_2013.] As public services and administration have become increasingly decentralized, states have often failed to provide scholars and policymakers with data to analyze these changes. Brazil is a felicitous exception. With an unparalleled wealth of data, I can provide a radiography tracing each personnel decision made by every elected mayor in Brazil from 2000 to 2016.^[Note that electoral data prior to 2000 is still incomplete and an ongoing effort by the Brazilian electoral court.] Over 5 thousand mayors taking office for each electoral cycle, accompanied by 30 thousand city councillors, and an average of 5 million bureaucrats work in each of these municipalities, and we have data for all of them. 

The time is ripe for a nuanced mapping of the divergent developmental paths of municipal public service delivery. Government provision of public services are the primary bloodline of those citizens born in poverty, and most desperately in need. As I later document, these are also where the worst quality healthcare and education services are provided. Understanding the roots in deficiencies in public service delivery demands theoretically and empirically grounded analysis. Ultimately, the welfare of citizens across the developing world depends on a better understanding of how these public service delivery systems are managed. Over this, the shadow of politics looms large. To confront it, we must shed light on it.

## The debate

In this introductory chapter, I lay out the theoretical debate which this dissertation enages with and contributes to. Due to the relatively large scale of this project, it intersects with multiple bodies of literature, which cannot all be addressed in the bounds of this chapter.^[I address particular bodies of literature in their relevant thematic chapters throughout the dissertation.] I opt to focus, in this introduction, on three main literatures which my theoretical argument speaks directly to. I first provide an analysis and critique of the Weberian model of bureaucracy, pushing for an explicit theorization of political administration in the developing world. The second body of literature focuses on the role of institutional legacies in determining state capacity, where I propose an agency-based theoretical approach to model dynamics of change in bureaucratic institutions.

Finally, I address the ways in which decentralization problematizes previous analyses of state institutions, while opening new avenues for theoretical and empirical inquiry. The Pandora's box of subnational heterogeneity, the "brown areas" as noted by @odonnell_state_1993, are a recent phenomenon. These are the result of political decisions reshaping administrative institutions at the subnational level, and as these responsibilities have been increasingly transferred to local politicians, understanding who they are, what are their strategies and payoffs becomes paramount to explaining variation in the quality of public services at the municipal level. To understand contemporary state capacity in an increasingly decentralized developing world, we must go local.^[@grindle_going_2007.]

## From Weber's shadow to political administration

Traditionally, analysis of public administration and bureaucracies in particular has drawn heavily upon the works of Max Weber.^[@weber_max_2009.] In the early 1980s, with the bringing back of the state and its administrative institutions, political scientists derived important lessons from Weber's description of the bureaucratic organization. Bureaucracies in the *modern* state were impersonal, rule-based, specialized. The state analogy to the capitalist enterprise, the bureaucracy was a calibrated, efficient machine with professionalized servants.^[@weber_max_2009.] Politics was not to mix with administration: administration, above all, was to be kept public.

Adapting this ideal-type to contemporary states, scholars mapped Weber's typology of bureaucracy as signs of a bureaucracy up to the standards of a strong, modern state.^[@skocpol_bringing_1985.] Among these features were an increasingly professionalized public workforce, sometimes conflated with the expansion in the number of civil servants through its territory.^[@mann_autonomous_1984.] One characteristic became especially salient as concerns expanded over political overreach: bureaucratic autonomy. Calls for a bureaucracy separate from political vicissitudes, an administrative apparatus insulated from myopic elected officials, became commonplace, especially in the developing world.^[Ironically, this was the exact opposite of what Weber posited in his description of bureaucracies, which were expected to conform to the mandate of political rulers.]

I will not provide an exhaustive treatment of the subject. Rather, I will focus on its general contours and how this conceptualization has limited political science in theoretically modeling and empirically analyzing public administration. In simple terms, bureaucratic autonomy denotes the protection of bureaucratic institutions from political manipulation by governing officials, be them democratically elected or not.^[@evans_embedded_1995.] It also denotes a certain degree of esprit de corps, an institutional cohesion that is derived from a sense of common purpose and longevity. This cohesion would be difficult to achieve if politicians could interfere with its internal workings every electoral cycle.^[@suleiman_dismantling_2013.]

A conceptual wall was built to separate the ideal-type of a Weberian, autonomous bureaucracy, free from political interference, and a world in which patrimonialism, the private use by politicians of public administration leads to corruption and inefficiency.^[@grindle_jobs_2012.] Other scholars, searching for empirical validation for these claims, provided historical qualitative and quantitative evidence that bureaucratic autonomy caused rapid economic growth and industrialization.^[@kohli_state-directed_2004, @evans_bureaucracy_1999.] These often normative claims on the need for depoliticized administration was contested, leading to heated debates over its merit - principally in the developed world - with the counterpush of New Public Management (NPM) principles and the need for bureaucratic accountability to elected officials.^[@osborne_banishing_1997.]

The debate on the desirability and consequences of bureaucratic autonomy in the developing world is *not* the one which this dissertation seeks to address. It proposes a new one. A systematic exploration of political administration, and the consequences of its various manifestations on the quality of public services. Politicians can and may dismantle bureaucracies, populating them with political loyalists who are unfitted for their positions.^[@suleiman_dismantling_2013.] That is not the only possible scenario. It may very well be the case that politicians can exercise management decisions in the service of improvements in bureaucratic structures, hiring meritocratically and improving the quality of these organizations.^[@grindle_good_2004.]

It is time to destigmatize political decisions over reshaping bureaucracies. Proponents of an autonomous civil service underemphasize the fact that these institutional reforms are the products of decisions made by politicians.^[While @grindle_jobs_2012 emp# References:hasizes the role of technocrats negotiating with politicians, @geddes_politicians_1994 highlights how investments in state capacity is an executive dilemma.] Moreover, we still know surprisingly little about how electoral concerns in particular and accountability more broadly affects piolitical decisions on how to manage bureaucracies.^[@gulzar_politicians_2017.] This dissertation represents an effort towards that direction, aligning itself with a growing literature on the political decisions to restructure bureaucratic structures.^[@raffler_does_2016, @brollo_victor_2017, @colonnelli_patronage_2017.]

Inserting public administrations within a political context necessarily puts them in motion. In the next section, I address the question of agency and structure. Inevitably, placing politicians as central actors reshaping the state's bureaucratic innards dialogues with a large literature on its historical institutional determinants.^[@skocpol_bringing_1985.] In this body of work, state institutions are often assumed to be slow-moving and not particularly amenable to short-term changes.^[See, for instance, the excellent discussion in @centeno_unpacking_2017.] In broad terms, this assessment is correct: it is hard for individual leaders to effect dramatic changes in the state. However, if we refine our analysis to particular branches of the bureaucracy, and in particular municipal bureaucracies, change is clearly the rule, not the exception.

## An agency-based approach to state capacity

Traditional accounts of state capacity, and bureaucratic institutions in particular, have emphasized reproduction and path-dependence over change.^[@pierson_increasing_2000.] These analytical tools provide limited leverage in analyzing different cycles of political administration - which align with electoral terms, as I later demonstrate - yet it is important to address their empirical contributions and theoretical assumptions. This dissertation dialogues with but ultimately parts ways with them. There are good reasons to emphasize and model change over reproduction, especifically in the context of executive actions over bureaucratic structures at the municipal level, which I outline in this section.

Note that agency-based change in state capacity does not imply an ahistorical lens. The institutional legacy of previous administrations is an important factor affecting the next political administration's decision. Once in office, politicians take into account inherited bureaucratic structures when restructuring them. However, these legacies do not exhaust the set of causal variables explaining bureaucratic structures at time $t + 1$. They are but one of the factors that politicians take into consideration in their decision-making, along with other time-varying factors such as legislative control, electoral payoffs to improvements in public service, and the individual characteristics of politicians.^[This has been modelled extensively in American Politics, primarily through the lens of executive-legislative bargaining. See @huber_bureaucratic_2004.]

I provide a review of extant literature on the prevalently historical-institutional analyses of state capacity, with a strong focus in the developing world. From the hapless origins in colonial exploitation, the absence of generalized war to contemporary structurally engendered practices of clientelism, there seems to be little current policymakers and scholars can do to effect positive, short-term change in state capacity.^[@acemoglu_colonial_2001, @engerman_factor_1997, @centeno_blood_1997.] Currently weak states have little to do today and much to blame for their unfortunate past. This leaves policymakers and scholars alike baffled as to how to enact policy reforms that can have a positive effect in public administration, as noted by @grindle_good_2004.

Take, for instance, the rich historical study presented in @centeno_blood_1997. Centeno highlights how a long colonial (and post-independence) history of dependence on commercial relations with external markets, through commodity-based exports, provided weak incentives for Latin American states to penetrate their territory and tax their own citizens. Contra Tilly, Latin American states waged the "wrong" kind of war, civil wars that depleted reserves while failing to provide incentives for the consolidation of state institutions, since these were too weak to effectively mobilize resources in a total war in the first place.^[@tilly_coercion_1992.] Weak domestic fiscal bases and limited penetration of their domestic territories left most of Latin America populated by weak states.

Another body of scholarly work focuses on factor endowments shaping the developmental path of state institutions in Latin America. In their study, @engerman_factor_1997 highlight how Latin American colonies, characterized by favorable conditions for plantation systems, produced highly unequal societies that locked in institutional arrangements that reproduced inequality in human capital, political power and inhibited economic development. In a similar vein, @acemoglu_colonial_2001 argue that high settler mortality discouraged investments in political institutions, in particular property rights to protect citizens from expropriation. Once set in place, these institutions were reproduced over time and explain different developmental paths.

My conceptual framework reinterprets path-dependence. On the one hand, institutional change is a clearly a costly endeavor. Changing inherited institutions requires confronting actors who may benefit from their reproduction.^[@pierson_increasing_2000.] However, rather than assuming that institutional reproduction will simply occur, I model and identify the conditions under which agents decide to modify institutional arrangements or not.^[For an excellent review, see @thelen_historical_1999.] Change is quotidian. To identify it, we must map what is time-varying and time-invariant, the actors which remain in power and the ones which replace them, sheding light on the vicissitudes of political life in a systematic and sequential manner.

To identify these gradual movements, it is necessary to be empirically precise about the object of inquiry. A lack of conceptual and empirical clarity means that broad claims about the "extractive" nature or "unequal" concentration of political power remain aphorisms, without a substantive measure to detect variance or absence thereof.^[@levitsky_variation_2009 stress the need for empirical measures of institutional strength.] Actors need to be well-defined as well. I link mayors and local legislators to the evolution of public services such as education and healthcare, while shedding light on the bureaucratic personnel responsible for bringing these to life. These interlinked actors and their strategic decisions form the basis of my argument.

Understanding and identifying change in state capacity requires defining the scope of analysis for this dissertation. I focus on a particular set of links in the causal chain: the bureaucratic personnel responsible for providing public services. Concretely, I focus on the municipal provision of education as the primary service which local bureaucrats, ranging from cabinet members, general managers, to frontline teachers and nurses are responsible for delivering in their every workday.

This is not a story of public administration alone. I build a theory of political action shaping bureaucratic personnel. While informally taking into account executive decisions to modify bureaucratic institutions, previous accounts rarely explore the full range and drivers of these decisions. In particular, seldom do we find an explicit treatment of the costs and benefits involved in the decision to invest in state capacity, what Geddes (1994) so aptly names the politician's dilemma. I focus on the electoral payoffs of public service provision: do incumbent mayors benefit from improvements in public service delivery? How does personnel management improve or undermine public services?

Leaders do not govern alone. For every elected mayor in Brazil, a set of legislators also take office. This diverse group of political actors interact strategically, and much of the executive-legislative bargain revolves around valuable buckets of jobs associated with cabinet positions, branches of government and municipal programs. A rich literature has emerged exploring the executive-legislative bargain, particularly in the U.S. context, but their application to the developing world context has been more limited.^[@moe_politics_1989, @mccarty_appointments_2004, and for an overview, @cameron_models_2004.] There is much to be gained in translation.

## The argument: a political administration of public services

This section started with a call for a conceptual change: embrace the political calculus embedded in administration and model it explicitly. In other words, move away from the ideal-type of a Weberian, autonomous bureaucracy and focus theoretically and empirically on political administration.^[@evans_embedded_1995.] Where does that leave us concretely? In this section, I present the conceptual building blocks of my argument. As premised, I focus on the decision-making process by political actors in reshaping the bureaucracy. Key among them are mayors, who hold discretion over whom to fire and recruit into the local administration, and city councillors, who exercise power over budgetary approval.

Understanding political decisions necessarily implies taking into account their consequences, in terms of costs and benefits. Agents in my theoretical model are forward-looking, and their payoff is structured sequentially. Here is an example to build intuition. A mayor is elected into office, and hopes to be reelected. In her first year of mandate, she decides how to restructure her educational staff. If the mayor eliminates experienced, educated school staff in exchange for political loyalists with limited experience, the quality of educational services will fall. If voters are aware of and care about educational services, conditional on a decrease in the quality of public services, the chances of the mayor being reelected decreases.

Moreover, mayors do not govern alone. A legislative opposition at the local city council has an interest in removing the executive leader from office. In Brazil, the local legislature has to approve the budget in order to fund public services. This game structure is conducive to a bargaining dynamic where legislators extract valuable public sector jobs to reward loyalists, in exchange for favorable votes for budgetary approval. Mayors have to engage in coalition building through the offer of valuable public sector jobs, in order to coopt enough legislative votes.

The simple example above illuminates the main actors and payoff structure in my theoretical argument. Concretely:

1. A mayor is elected into office and seeks reelection.
2. Voters (potentially) observe and care about the quality of public services, rewarding good performance.
3. Legislators in the city council seek to maximize their share of public sector jobs.

My theory builds on an extensive literature in the electoral accountability literature, modeling public goods provision as an electoral game played between voters who want to induce good behavior and political incumbents bidding for reelection. Expanding on seminal models by @barro_control_1973 and @ferejohn_incumbent_1986, political economists have explored theories incorporating electoral accountability as an incentive for shaping the behavior of elected officials. The crux of the argument relies on the desire for reelection, which motivates politicians to put effort into providing voters to reelect them.^[@coate_form_1995 and @besley_principled_2006 incorporate voters updating Bayesian beliefs about politician types, a feature applied in my model.]

To summarize, a new mayor is elected into office and has the power to restructure the local bureaucracy. To be reelected, she has to convince the electorate that she will provide high quality public services in her second term, and to do so wants to minimize bureaucratic turnover. However, she must also coopt the legislature to approve the local budget by divving up a share of the bureaucratic pie for patronage.^[This aligns closely to previous studies on the use of ministerial positions to gain support from opposition members at the federal level. See @loureiro_politica_1999, @loureiro_radiografia_2014, @lopez_cargos_2018.] The model highlights the tradeoff executive politicians face between investing in state capacity and garnering legislative votes.

Instead of assuming that politicians can set the quality of public goods provision, I model it as the probabilistic outcome of an investment in bureaucratic quality and legislative support. Producing better public goods requires an experienced and professional bureaucracy and legislative support. Reshuffling the bureaucracy is costly due to the loss of professional expertise accumulated by the inherited staff, but this underlying capacity is meaningless if the legislative does not grant its approval. The executive does not always control the legislative chamber once in office, and have to coopt them into supporting their agenda.^[Analogous to the concept of minority presidents in the literature on coalitional presidentialism. See @figueiredo_presidential_2000.]

The mayor's strategy centers around a key part of her political resources: a set of public sector jobs is available to the executive for redistribution. These are a valuable resource for cooptation.^[Mayors enjoy full discretion into how to appoint workers into the public sector and often resort to distributing these jobs to appease members of the legislative.] However, when doing so executive leaders face a dilemma. The mayor can invest in state capacity, retaining expertise and reaping benefits from better public service provision. However, doing so raises the possibility of retaliation by the opposition, who can threaten to oppose budgetary approval. This is the executive's dilemma.^[@geddes_politicians_1994.]

